[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bonding-curve = "GvFsepxBQ2q8xZ3PYYDooMdnMBzWQKkpKavzT7vM83rZ"
genesis = "2vgQn1c2JPWGHYcjhBcdeXKCQCSWfs8gYn6CcNhMKwMG"
liquidity-pool = "B24yupzEDjF7Z9frnDG16uAwH1ZYfB57kuzh8jwDsL83"
n-dollar = "3Mdve11qmHuVZVe9YgCzA1d3hcjyamm2Jiz3VfHSJgEQ"
referral-rewards = "8YxBBLHPCAMQWkxD8WD1X1XyuUZH5u58wB8R4Q31eGCb"
token-distributor = "2Hy1wGdC5iqceaTnZC1qJeuoM4s6yEKHbYcjMMpbKYqp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
